import type { Prisma } from "@prisma/client"

export const garmentSeedData = [
  { code: "5001", altCode: "", brandName: "AS Colour", name: "Staple Tee", color: "", type: "TSHIRT", basePrice: 4.65, extraSizeCost: null, tags: "AS Colour, 5001, Staple" },
  { code: "5001C", altCode: "", brandName: "AS Colour", name: "Staple Camo Tee", color: "", type: "TSHIRT", basePrice: 6.65, extraSizeCost: null, tags: "5001c, camo, staple" },
  { code: "5020", altCode: "", brandName: "AS Colour", name: "Staple L/S Tee", color: "", type: "TSHIRT", basePrice: 6.65, extraSizeCost: null, tags: "5020, staple, long sleeve" },
  { code: "5020G", altCode: "", brandName: "AS Colour", name: "Staple Organic L/S Tee", color: "", type: "TSHIRT", basePrice: 6.9, extraSizeCost: null, tags: "5020G, Staple, organic, organic long sleeve, long sleeve" },
  { code: "5026", altCode: "", brandName: "AS Colour", name: "Classic Tee", color: "", type: "TSHIRT", basePrice: 6.5, extraSizeCost: null, tags: "5026, AS Colour, classic tee" },
  { code: "5030", altCode: "", brandName: "AS Colour", name: "Box Tee", color: "", type: "TSHIRT", basePrice: 7.15, extraSizeCost: null, tags: "Box Tee, AS Colour, 5030" },
  { code: "5031", altCode: "", brandName: "AS Colour", name: "Box L/S Tee", color: "", type: "TSHIRT", basePrice: 8.95, extraSizeCost: null, tags: "5031. box, long sleeve" },
  { code: "5040", altCode: "", brandName: "AS Colour", name: "Staple Stone Wash Tee", color: "", type: "TSHIRT", basePrice: 7.8, extraSizeCost: null, tags: "5040, Staple Stone Wash Tee, washed, stone washed" },
  { code: "5050", altCode: "", brandName: "AS Colour", name: "Block Tubular Tee", color: "", type: "TSHIRT", basePrice: 3.25, extraSizeCost: null, tags: "5026, Block Tubular Tee" },
  { code: "5054", altCode: "", brandName: "AS Colour", name: "Block L/S Tee", color: "", type: "TSHIRT", basePrice: 4.8, extraSizeCost: null, tags: "5054. block, long sleeve" },
  { code: "5071", altCode: "", brandName: "AS Colour", name: "Classic L/S Tee", color: "", type: "TSHIRT", basePrice: 8.4, extraSizeCost: null, tags: "5071, Classic, long sleeve" },
  { code: "5080", altCode: "", brandName: "AS Colour", name: "Heavy Tee", color: "", type: "TSHIRT", basePrice: 7.7, extraSizeCost: null, tags: "5080, Heavy Tee" },
  { code: "5081", altCode: "", brandName: "AS Colour", name: "Heavy L/S Tee", color: "", type: "TSHIRT", basePrice: 10.2, extraSizeCost: null, tags: "5081, long sleeve" },
  { code: "5082", altCode: "", brandName: "AS Colour", name: "Heavy Faded Tee", color: "", type: "TSHIRT", basePrice: 7.7, extraSizeCost: null, tags: "5082, Heavy Faded Tee, faded" },
  { code: "5083", altCode: "", brandName: "AS Colour", name: "Heavy Faded L/S Tee", color: "", type: "TSHIRT", basePrice: 10.2, extraSizeCost: null, tags: "5083, Faded, faded long sleeve" },
  { code: "5085", altCode: "", brandName: "AS Colour", name: "Stone Wash Heavy Tee", color: "", type: "TSHIRT", basePrice: 8.25, extraSizeCost: null, tags: "5085, Stone Wash Heavy Tee, stone wash" },
  { code: "5086", altCode: "", brandName: "AS Colour", name: "Heavy Faded Minus Tee [-5cm]", color: "", type: "TSHIRT", basePrice: 7.7, extraSizeCost: null, tags: "5086, Heavy Faded Minus Tee [-5cm], faded, minus" },
  { code: "5102", altCode: "", brandName: "AS Colour", name: "Stencil Hood", color: "", type: "TSHIRT", basePrice: 19.55, extraSizeCost: null, tags: "5102, stencil hood" },
  { code: "5111", altCode: "", brandName: "AS Colour", name: "Standard Hood", color: "", type: "TSHIRT", basePrice: 12.25, extraSizeCost: null, tags: "5111, Standard hoodie" },
  { code: "5145", altCode: "", brandName: "AS Colour", name: "Heavy Crew", color: "", type: "TSHIRT", basePrice: 19.8, extraSizeCost: null, tags: "5145, sweater, heavy crew" },
  { code: "5146", altCode: "", brandName: "AS Colour", name: "Heavy Hood", color: "", type: "TSHIRT", basePrice: 22.25, extraSizeCost: null, tags: "5146, heavy hood" },
  { code: "5161", altCode: "", brandName: "AS Colour", name: "Relax Hood", color: "", type: "TSHIRT", basePrice: 16.95, extraSizeCost: null, tags: "5161, relax hood, hoodie" },
  { code: "5165", altCode: "", brandName: "AS Colour", name: "Relax Faded Crew", color: "", type: "TSHIRT", basePrice: 16.05, extraSizeCost: null, tags: "5165, relax faded crew, faded, faded sweater" },
  { code: "5166", altCode: "", brandName: "AS Colour", name: "Relax Faded Hood", color: "", type: "TSHIRT", basePrice: 18.05, extraSizeCost: null, tags: "5166, relax faded hood" },
  { code: "5171", altCode: "", brandName: "AS Colour", name: "Box Hood", color: "", type: "TSHIRT", basePrice: 19.55, extraSizeCost: null, tags: "5171, box hood" },
  { code: "B653", altCode: "BC653", brandName: "Beechfield", name: "Beechfield Low Profile 6 Panel Dad Cap", color: "", type: "TSHIRT", basePrice: 3.2, extraSizeCost: null, tags: "bb653, beechfield, cap, dad cap, BC653" },
  { code: "BB45", altCode: "BC45", brandName: "Beechfield", name: "Original cuffed beanie", color: "", type: "TSHIRT", basePrice: 2, extraSizeCost: null, tags: "Beanie, beechfield, BB45, BC45" },
  { code: "CV3001", altCode: "3001", brandName: "Bella Canvas", name: "Unisex Crew Neck T-Shirt", color: "Colours", type: "TSHIRT", basePrice: 4.8, extraSizeCost: null, tags: "Bella Canvas, tee, CV3001, 3001" },
  { code: "CV3001", altCode: "", brandName: "Bella Canvas", name: "Canvas Unisex Crew Neck T-Shirt", color: "Whites", type: "TSHIRT", basePrice: 4.8, extraSizeCost: null, tags: "Bella Canvas, tee, white, size note: 2XL: 5, 4 / 3XL: 7" },
  { code: "GD01", altCode: "64000", brandName: "Gildan", name: "Gildan SoftStyle Adult T-Shirt", color: "Colours", type: "TSHIRT", basePrice: 2.25, extraSizeCost: 0.7, tags: "GD01, 64000, SOFT, SOFTSTYLE, GILDAN" },
  { code: "GD01", altCode: "64000", brandName: "Gildan", name: "Gildan SoftStyle Adult T-Shirt", color: "Whites", type: "TSHIRT", basePrice: 1.85, extraSizeCost: 0.6, tags: "GD01, 64000, GILDAN SOFT, SOFTSTYLE" },
  { code: "GD02", altCode: "2000", brandName: "Gildan", name: "Gildan Ultra Cotton T-Shirt", color: "Colours", type: "TSHIRT", basePrice: 2.8, extraSizeCost: 1.1, tags: "Gildan Ultra, Ultra, GD02, 2000" },
  { code: "GD02", altCode: "2000", brandName: "Gildan", name: "Gildan Ultra Cotton T-Shirt", color: "Whites", type: "TSHIRT", basePrice: 2.35, extraSizeCost: 1.1, tags: "gildan ultra, GD02, 2000, ultra" },
  { code: "GD05", altCode: "5000", brandName: "Gildan", name: "Gildan Heavy Cotton T-Shirt", color: "Colours", type: "TSHIRT", basePrice: 2.4, extraSizeCost: 0.9, tags: "Gildan, tee, black, HEAVY, GD05, 5000" },
  { code: "GD05", altCode: "5000", brandName: "Gildan", name: "Gildan Heavy Cotton T-Shirt", color: "Whites", type: "TSHIRT", basePrice: 1.95, extraSizeCost: 0.9, tags: "Gildan, tee, white, GD05, 5000, HEAVY" },
  { code: "GD14", altCode: "2400", brandName: "Gildan", name: "Gildan Ultra Cotton Long Sleeve T-Shirt", color: "Colours", type: "LONGSLEEVE", basePrice: 5.7, extraSizeCost: 2, tags: "Gildan, long sleeve, black, GD14, 2400, ULTRA, GILDAN ULTRA" },
  { code: "GD14", altCode: "2400", brandName: "Gildan", name: "Gildan Ultra Cotton Long Sleeve T-Shirt", color: "Whites", type: "LONGSLEEVE", basePrice: 4.7, extraSizeCost: 2, tags: "GILDAN ULTRA LONG SLEEVE, LONG SLEEVE, GD14, ULTRA, 2400" },
  { code: "GD21", altCode: "H000", brandName: "Gildan", name: "Gildan Hammer Heavyweight T-Shirt", color: "Colours", type: "TSHIRT", basePrice: 3.15, extraSizeCost: 1.2, tags: "Gildan, tee, black, HAMMER, H000, GD21" },
  { code: "GD21", altCode: "H000", brandName: "Gildan", name: "Gildan Hammer Heavyweight T-Shirt", color: "Whites", type: "TSHIRT", basePrice: 2.65, extraSizeCost: 1, tags: "Gildan, tee, white, GD21, H000" },
  { code: "GD56", altCode: "18000", brandName: "Gildan", name: "GI18000 HEAVY SWEATSHIRT", color: "Colours", type: "HOODIE", basePrice: 5.9, extraSizeCost: 0.5, tags: "Gildan, sweatshirt, black, GD56, 18000" },
  { code: "GD56", altCode: "18000", brandName: "Gildan", name: "GI18000 HEAVY SWEATSHIRT", color: "Whites", type: "HOODIE", basePrice: 5.4, extraSizeCost: 1.65, tags: "Gildan, sweatshirt, white, GD56, 18000" },
  { code: "GD57", altCode: "18500", brandName: "Gildan", name: "Gildan Heavy Blend Hooded Sweatshirt", color: "Colours", type: "HOODIE", basePrice: 8.25, extraSizeCost: 2, tags: "GD57, 18500, GILDAN HEAVY HOODIE, HOODIE, HEAVY" },
  { code: "GD57", altCode: "18500", brandName: "Gildan", name: "Gildan Heavy Blend Hooded Sweatshirt", color: "Whites", type: "HOODIE", basePrice: 8.25, extraSizeCost: 2, tags: "Gildan, hoodie, white, GD57, 18500" },
  { code: "JH001", altCode: "", brandName: "AWDis", name: "AWDis College hoodie", color: "Whites", type: "HOODIE", basePrice: 9.5, extraSizeCost: 1.5, tags: "AWDis, hoodie, white, college, JH001" },
  { code: "JH001", altCode: "", brandName: "AWDis", name: "AWDis College hoodie", color: "colours", type: "HOODIE", basePrice: 9.5, extraSizeCost: 1.5, tags: "AWDis, JH001, College" },
  { code: "W101", altCode: "WM101", brandName: "Westford Mill", name: "Westford Mill Bag For Life - Long Handles", color: "", type: "TSHIRT", basePrice: 1.5, extraSizeCost: null, tags: "Westford Mill, tote, W101" },
  { code: "W265", altCode: "WM265", brandName: "Westford Mill", name: "Westford Mill Organic Premium Cotton Maxi Tote Bag", color: "", type: "TSHIRT", basePrice: 3.6, extraSizeCost: null, tags: "Westford Mill, tote, W265, WM265" },
] satisfies Prisma.GarmentCreateManyInput[]

export const garmentMarkupSeedData = [
  { garmentType: "HOODIE", markupValue: 5 },
  { garmentType: "LONGSLEEVE", markupValue: 3.5 },
  { garmentType: "TSHIRT", markupValue: 3 },
] satisfies Prisma.GarmentMarkupCreateManyInput[]

export const printPriceSeedData = [
  { colorCount: 1, qtyMin: 50, qtyMax: 99, productionPrice: 1.4, pinsPrice: 1.54 },
  { colorCount: 1, qtyMin: 100, qtyMax: 249, productionPrice: 1.15, pinsPrice: 1.26 },
  { colorCount: 1, qtyMin: 250, qtyMax: 499, productionPrice: 1, pinsPrice: 1.1 },
  { colorCount: 1, qtyMin: 500, qtyMax: 999, productionPrice: 0.9, pinsPrice: 0.99 },
  { colorCount: 1, qtyMin: 1000, qtyMax: 2000, productionPrice: 0.75, pinsPrice: 0.82 },
  { colorCount: 2, qtyMin: 50, qtyMax: 99, productionPrice: 1.6, pinsPrice: 1.76 },
  { colorCount: 2, qtyMin: 100, qtyMax: 249, productionPrice: 1.4, pinsPrice: 1.54 },
  { colorCount: 2, qtyMin: 250, qtyMax: 499, productionPrice: 1.25, pinsPrice: 1.38 },
  { colorCount: 2, qtyMin: 500, qtyMax: 999, productionPrice: 1.2, pinsPrice: 1.32 },
  { colorCount: 2, qtyMin: 1000, qtyMax: 2000, productionPrice: 1.05, pinsPrice: 1.16 },
  { colorCount: 3, qtyMin: 50, qtyMax: 99, productionPrice: 2.15, pinsPrice: 2.37 },
  { colorCount: 3, qtyMin: 100, qtyMax: 249, productionPrice: 1.7, pinsPrice: 1.87 },
  { colorCount: 3, qtyMin: 250, qtyMax: 499, productionPrice: 1.45, pinsPrice: 1.6 },
  { colorCount: 3, qtyMin: 500, qtyMax: 999, productionPrice: 1.4, pinsPrice: 1.54 },
  { colorCount: 3, qtyMin: 1000, qtyMax: 2000, productionPrice: 1.25, pinsPrice: 1.38 },
  { colorCount: 4, qtyMin: 50, qtyMax: 99, productionPrice: 2.6, pinsPrice: 2.86 },
  { colorCount: 4, qtyMin: 100, qtyMax: 249, productionPrice: 2.35, pinsPrice: 2.59 },
  { colorCount: 4, qtyMin: 250, qtyMax: 499, productionPrice: 1.7, pinsPrice: 1.87 },
  { colorCount: 4, qtyMin: 500, qtyMax: 999, productionPrice: 1.6, pinsPrice: 1.76 },
  { colorCount: 4, qtyMin: 1000, qtyMax: 2000, productionPrice: 1.4, pinsPrice: 1.54 },
  { colorCount: 5, qtyMin: 50, qtyMax: 99, productionPrice: 3.25, pinsPrice: 3.58 },
  { colorCount: 5, qtyMin: 100, qtyMax: 249, productionPrice: 2.5, pinsPrice: 2.92 },
  { colorCount: 5, qtyMin: 250, qtyMax: 499, productionPrice: 1.95, pinsPrice: 2.14 },
  { colorCount: 5, qtyMin: 500, qtyMax: 999, productionPrice: 1.9, pinsPrice: 2.09 },
  { colorCount: 5, qtyMin: 1000, qtyMax: 2000, productionPrice: 1.7, pinsPrice: 1.87 },
  { colorCount: 6, qtyMin: 50, qtyMax: 99, productionPrice: 4.05, pinsPrice: 4.46 },
  { colorCount: 6, qtyMin: 100, qtyMax: 249, productionPrice: 2.65, pinsPrice: 2.75 },
  { colorCount: 6, qtyMin: 250, qtyMax: 499, productionPrice: 2.2, pinsPrice: 2.42 },
  { colorCount: 6, qtyMin: 500, qtyMax: 999, productionPrice: 2.15, pinsPrice: 3.27 },
  { colorCount: 6, qtyMin: 1000, qtyMax: 2000, productionPrice: 2, pinsPrice: 2.2 },
  { colorCount: 7, qtyMin: 50, qtyMax: 99, productionPrice: 4.8, pinsPrice: 5.28 },
  { colorCount: 7, qtyMin: 100, qtyMax: 249, productionPrice: 2.8, pinsPrice: 3.08 },
  { colorCount: 7, qtyMin: 250, qtyMax: 499, productionPrice: 2.5, pinsPrice: 2.75 },
  { colorCount: 7, qtyMin: 500, qtyMax: 999, productionPrice: 2.45, pinsPrice: 2.7 },
  { colorCount: 7, qtyMin: 1000, qtyMax: 2000, productionPrice: 2.3, pinsPrice: 2.53 },
  { colorCount: 8, qtyMin: 50, qtyMax: 99, productionPrice: 5.45, pinsPrice: 6 },
  { colorCount: 8, qtyMin: 100, qtyMax: 249, productionPrice: 3.1, pinsPrice: 3.41 },
  { colorCount: 8, qtyMin: 250, qtyMax: 499, productionPrice: 2.8, pinsPrice: 3.08 },
  { colorCount: 8, qtyMin: 500, qtyMax: 999, productionPrice: 2.75, pinsPrice: 3.03 },
  { colorCount: 8, qtyMin: 1000, qtyMax: 2000, productionPrice: 2.6, pinsPrice: 2.86 },
  { colorCount: 9, qtyMin: 50, qtyMax: 99, productionPrice: 6.1, pinsPrice: 6.71 },
  { colorCount: 9, qtyMin: 100, qtyMax: 249, productionPrice: 3.4, pinsPrice: 3.74 },
  { colorCount: 9, qtyMin: 250, qtyMax: 499, productionPrice: 3.1, pinsPrice: 3.41 },
  { colorCount: 9, qtyMin: 500, qtyMax: 999, productionPrice: 3.05, pinsPrice: 3.36 },
  { colorCount: 9, qtyMin: 1000, qtyMax: 2000, productionPrice: 2.9, pinsPrice: 3.19 },
] satisfies Prisma.PrintPriceCreateManyInput[]
