-- AlterTable
ALTER TABLE "Garment" ADD COLUMN "altCode" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Garment" ADD COLUMN "brandName" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Garment" ADD COLUMN "color" TEXT NOT NULL DEFAULT '';
